### ISSUE TITLE
Media queries for job postings?

### ISSUE THREAD

**Issue by markymauro13** [NewGradNomad/newgradnomad.com#101]
May or may not need, my phone puts third tag on a new line

![image](https://user-images.githubusercontent.com/18267324/219793937-e999dcf2-257f-471a-beef-90fe029f0b09.png)

**Comment by KennethDoerflein** [comment]
Will be on multiple lines anyway once the actual tags are there, some are pretty long.

**Comment by KennethDoerflein** [comment]
Fixed with #163
